### ISSUE TITLE
DatetimePicker 时间选择器组件样式问题

### ISSUE THREAD

**Issue by aifuxi** [jd-ftf/wot-design#223]
版本2.1.0
错误图如下
![image](https://user-images.githubusercontent.com/65325004/98444235-80142600-214b-11eb-8719-0b20e24e7c9b.png)

**Comment by HXCStudio123** [comment]
下个版本修复，感谢使用♪(･ω･)ﾉ

**Comment by yawuling** [comment]
2.2.0 版本已修复
