### ISSUE TITLE
新增组件

### ISSUE THREAD

**Issue by xianguozhu** [jd-ftf/wot-design#260]
添加日历组件和骨架

**Comment by yawuling** [comment]
日历组件正在规划中，骨架的话之前有考虑过添加，但实际发现意义不大，只能布局出简单的页面展示，对于稍微复杂的页面就无法应用了

**Comment by yawuling** [comment]
日历组件已新增，骨架屏暂时没在计划中

**Comment by xianguozhu** [comment]
Toast 轻提示 没有关闭回调的方法吗



在 2021-04-25 13:49:01，"zhongzhijie" ***@***.***> 写道：

日历组件已新增，骨架屏暂时没在计划中

**Comment by yawuling** [comment]
> Toast 轻提示 没有关闭回调的方法吗 在 2021-04-25 13:49:01，"zhongzhijie" ***@***.***> 写道： 日历组件已新增，骨架屏暂时没在计划中 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没有，这边记一下，等 618 之后找个时间加上
