### ISSUE TITLE
Tabbar status display wrong with a string type value 

### ISSUE THREAD

**Issue by lsr1962** [jd-ftf/wot-design#274]
Version
2.2.1

Steps to reproduce
Set Tabbar-item's props **name** & Tabbar's **value** to a String Type value.

What is expected?
Display current tabbar-item Correctly。

What is actually happening?
Miss active status
![1](https://user-images.githubusercontent.com/12226709/109928587-90ef3580-7d00-11eb-81f5-2217f9573e6a.png)
![2](https://user-images.githubusercontent.com/12226709/109928595-93518f80-7d00-11eb-9aa6-b0b4797cfc80.png)

.

**Comment by yawuling** [comment]
2.3.0 版本已修复
