### ISSUE TITLE
[Bug Report] wd-datetime-picker 中设置minDate  设置的 v-model 不会刷新页面

### ISSUE THREAD

**Issue by LeonGong** [jd-ftf/wot-design#278]
wd-datetime-picker 用来配置用户生日信息。

**Comment by yawuling** [comment]
辛苦提供下可复现的示例代码

**Comment by LeonGong** [comment]
```
 <wd-datetime-picker
          v-model="birthday"
          :minDate="minDate"
          label="生日"
          :columns-height="180"
          type="date"
          ref="birthday"
        ></wd-datetime-picker>

```...
mounted(){
...
this.birthday = new Date(
        birthDay.format("YYYY"),
        birthDay.format("M")-1,
        birthDay.format("D")
      );  
...
}

**Comment by yawuling** [comment]
> ```
>  <wd-datetime-picker
>           v-model="birthday"
>           :minDate="minDate"
>           label="生日"
>           :columns-height="180"
>           type="date"
>           ref="birthday"
>         ></wd-datetime-picker>
> 
> ```...
> mounted(){
> ...
> this.birthday = new Date(
>         birthDay.format("YYYY"),
>         birthDay.format("M")-1,
>         birthDay.format("D")
>       );  
> ...
> }
> ```
mounted 里的 birthDay 辛苦提供下示例值，以及 minDate 提供下示例值

**Comment by LeonGong** [comment]
Data{
return {
miniDate: new Date(1970,0,1),
birthDay:""
}

mount(){
this.birthDay = new Date(2021,0,1);//就是这个没有生效；
}

**Comment by yawuling** [comment]
好的，感谢反馈，这个问题我们看下

**Comment by yawuling** [comment]
已发布 2.3.2 版本修复该问题
