### ISSUE TITLE
checkbox渲染问题

### ISSUE THREAD

**Issue by zydwcp1113** [jd-ftf/wot-design#307]
<wd-checkbox value="jingmai">京麦</wd-checkbox>
                  <template v-for="item in currentDataSet">
                     <wd-checkbox :value="item.gdl_id" :key="item.gdl_id">{{item.gdl_name}}</wd-checkbox>
                  </template>
              </div>

单独写死能正常渲染，使用for循环构造就会渲染不出来

**Comment by yawuling** [comment]
可能是你的数组没有按照 vue 的要求响应式赋值，你先排查下，我这边是可以的
