### ISSUE TITLE
Search组件 type为number 清空输入值出现NaN

### ISSUE THREAD

**Issue by tclyjy** [jd-ftf/wot-design#327]
问题：Search组件 type为number 清空输入值出现NaN
原因分析：
<img width="720" alt="wecom-temp-cf86b9225e96e74efa833c4cec126305" src="https://user-images.githubusercontent.com/16618594/125414393-64227336-42ac-4a3e-af5f-c7754f5693bc.png">
解决：
```javascript
// wot-design/packages/search/src/main.vue
input(e) {
  if (this.type === 'number') {
    e.target.value = e.target.value.replace(/[^0-9]/g, '')
  }
  this.$emit('input', this.type === 'number' && e.target.value ? parseInt(e.target.value) : e.target.value)
},
```

**Comment by Gkxie** [comment]
老哥要不要提个PR解决下。
