### ISSUE TITLE
请问wot-design组件库还有在维护吗，我看已经很久没更新了

### ISSUE THREAD

**Issue by Moonofweisheng** [jd-ftf/wot-design#359]

**Comment by Gkxie** [comment]
前 core contributer：走的时候公司架构调整了好几轮了，已经很久没人维护了。

**Comment by Moonofweisheng** [comment]
> 前 core contributer：走的时候公司架构调整了好几轮了，已经很久没人维护了。

😂太遗憾了，感觉还不错的。
